#!/bin/bash
## Typical args app=ecd://epls.coe.fsu.edu/P4test level=DEBUG
## Optional args clean=TRUE (default FALSE) evidence=<file>.json
if [ $# -lt 1 ]; then
    echo "Usage:  EIEvent appStem [--override] [--noprep] [--level=DEBUG] [Rlogfile]"
    exit(1)
fi
R_HOME=$(R RHOME)
EI_SCRIPTPATH=$(${R_HOME}/bin/Rscript -e 'cat(file.path(.libPaths()[1], "EIEvent", "config"))')
Rlogfile="${!#}.Rout"
appArgs="app=${@:1:$#-1}"
echo "Starting Evidence Identification " $appArgs $Rlogfile
nohup R  --slave "--args $appArg" <"$EI_SCRIPTPATH/RunEIEvent.R" >&"$Rlogfile" &
